### PR TITLE
Fix search cursor color and initial bottom sheet height

### PR DESCRIPTION
**Pull request by cizmarf**
The cursor color in the search box was always white, now it is set to provided text style color.
The Bottom Sheet default height was too small and the sheet was hidden behind keyboard.
Also downgrade intl version as it is not working in the current dev.

### CODE REVIEW

**Comment by cedvdb** [comment]
Do you have a before after view of the fix ? Also why the downgrade of intl ?

**Comment by cizmarf** [comment]
There is a commit upgrading intl version in dev, but no new package version. Flutter pub fetched the package from the head of dev branch. 

I am not sure why the last commit check failed. Actually the feature can be provided by a better way.

Before:
Simulator Screen Shot - iPhone 14 Pro Max - 2023-02-15 at 22 11 17

After:
IMG_7393

**Comment by cedvdb** [comment]
Here is the failure You can see it in details I believe, or maybe you don't have access to that

image

**Comment by cedvdb** [comment]
I'm reverting this as there seem to be additional code unrelated in a stack widget. Could you provide more info about that ?

**Comment by cizmarf** [comment]
Ah sorry I committed a part of different feature in the last commit. It should use the error text style provided in decoration.
I can delete it from this branch or add the complete code of this feature. What would you like?

**Comment by cedvdb** [comment]
I would like separate Pull requests for separate fixes. thanks

**Pull request merged**
