### PR TITLE
Update to use latest version of circle_flags.

### PR DESCRIPTION
**Pull request by iamriajul**
circle_flags now use SVG for a smaller memory footprints.

### CODE REVIEW

**Comment by iamriajul** [comment]
tests have been fixed, pumpAndSettle wasn't working because there is an animated widget (CircularProgressIndicator) being used in the latest version of circle_flags. That's why I needed to use the pump method with Duration, which solves the issue.

**Comment by iamriajul** [comment]
Oops! by mistake, I closed the issue. Now everything should be fine, Build workflow should not fail now if you run.

**Comment by iamriajul** [comment]
Thanks, @cedvdb for being so responsive.

**Comment by cedvdb** [comment]
published

**Pull request merged**
