### PR TITLE
feat(validator): allow to use custom validator

### PR DESCRIPTION
**Pull request by emri99**
### PR Type
New feature

### BC Break
Yes, see CHANGELOG file

### Description
Allow end user to define a custom validator

### Sample
```
PhoneFormField(
  validator: (PhoneNumber? phoneNumber) {
    if (phoneNumber == null) {
      return null;
    }
    final PhoneParser parser = PhoneParser();
    if (!parser.validate(phoneNumber, PhoneNumberType.mobile)) {
      return 'not a mobile line';
    }
    if (!parser.validate(phoneNumber)) {
      return 'invalid format';
    }
  },
);
```

### CODE REVIEW

**Comment by cedvdb** [comment]
In your example you use the PhoneParser with the phoneNumberType.

I assume that's just an example you picked to be explicit. However I'm still wondering what's the use case where you'd not want the validation to happen by this lib. I can see one:

  - The validation that happens in the library is faulty

**Comment by emri99** [comment]
Not only, in my case I want 2 différents messages depending on invalid or not expected type. I picked up this from my real project :)

**Comment by cedvdb** [comment]
I see the need. I've one question: In your current project would it make sens to use a `BasePhoneFormField` as it would be mostly UI, and do the validation, formatting manually ?

**Comment by emri99** [comment]
Another common use case is to set this field required as well as a phone number validator.

We can even to expose a validator class, so that it can used as follow:

```
PhoneFormField(
  // message argument is optional
  validator: PhoneValidator.compose([
    PhoneValidator.required(context, message: "This field is required"),
    PhoneValidator.invalid(context, message: "Invalid phone number"),
    PhoneValidator.type(context, PhoneNumberType.mobile, message: "Not a mobile phone number"),
  ]),
)
```

This way, end user may use multiple validators depending on the use case and define a specific message for each type if wanted. Inspired by [flutter_form_builder validation](https://pub.dev/packages/flutter_form_builder#using-multiple-validators)

**Comment by emri99** [comment]
I've done the changes PARTIALLY : 
* PhoneValidator is created with defaults error messages, no localization texts added for now.
* I don't change the `phoneNumberType` usage for now.


This may be confusing to have `phoneNumberType`, `errorText` message, and `validator`, I can see 2 ways of handling this :
1. perform an assertion on PhoneFormField constructor to check that `phoneNumberType` and `validator` cannot be defined simultaneously, and then internally : 
   * when neither `phoneNumberType` nor `validator` are supplied : create the invalid validator (using `errorText` if supplied) 
   * when `phoneNumberType` is supplied : create the type validator (using `errorText` if supplied)  
   * in all case : remove the default `errorText` value and let property be nullable as this is now handle by the validator itself
2. remove the `phoneNumberType` & `errorText` and let user defines it own navigator if needed, otherwise add a default invalid validator

In both case above, I suppose it makes sense to always add an invalid validator when user does not explicitly set a validator.
In rare case where the user don't want this default validator, it can be disable by adding a fake validator : ```(PhoneNumber? p) => null```

IMHO I think that solution 2 is more reliable : less conditions to test, less tests to write, less complexity, so less code and less bugs. (Keep in mind, that solution 2 is however a BC break change)

Any ideas, recommandations before I perform these latests changes ?

**Comment by cedvdb** [comment]
In your last message, are you using the word `navigator` incorrectly or is it on purpose ?

For example here

> remove the phoneNumberType & errorText and let user defines it own navigator if needed, otherwise add a default invalid validator


A Validator interface could do the work and the user can give a new one (deprecation of old fields). I like the idea of a class, because it would allow for compose method like in your example.

**Comment by emri99** [comment]
It's an error, should be `validator` ;)

**Comment by cedvdb** [comment]
I'm not against breaking changes as this library is kind of young it's better to do those changes now, with deprecation when possible is the way to go.

**Comment by emri99** [comment]
My initial use case was to have 2 distincts message for invalid & type not allowed.

But with your remark, I think you're right, and exposing an invalid validator, with an optional type may be sufficient, just a bit less explicit.

Moreover, my original use case is still available like this:
```
  validator: PhoneValidator.compose([
    PhoneValidator.invalid(context, errorText: "Invalid phone number"),
    PhoneValidator.invalid(context, type: PhoneNumberType.mobile, errorText: "Not a mobile phone number"),
    // ...
  ]),
```

Is this what you had in mind ?

**Comment by cedvdb** [comment]
I want to deprecate the phoneNumberType property to completely remove if in a future release. Or alternatively we could completely remove it now but that introduce a breaking change without warning.

**Comment by emri99** [comment]
I will update this way. Good practices are good practices, whatever amount of users ;)

* What about the `errorText` property, do you think it makes sense to remove it in a future release too (and thus, deprecate it too) ? My opinion is yes, looking forward to hear yours ;)
* Do you want me to write a migration guide ?

> But with your remark, I think you're right, and exposing an invalid validator, with an optional type may be sufficient, just a bit less explicit.

* May be you tell me what you think of my proposition above when you had time to ?

Sorry for multiple questions in one, as I will be offline in a moment for the next few hours and will try to finish this tonight, this might be helpful for me to have your opinion when I will get back so I can make the changes in the expected way ;)

**Comment by cedvdb** [comment]
> What about the errorText property, do you think it makes sense to remove it in a future release too (and thus, deprecate it too) ? 

Yes, it is now the responsibility of the validator.

> Do you want me to write a migration guide ?

In my opinion if the validation is explained in the documentation and the changelog is explicit, then a migration guide is not needed.

> But with your remark, I think you're right, and exposing an invalid validator, with an optional type may be sufficient, just a bit less explicit.

Well I'm not sure and I was not sure when writing it either. I hoped the discussion would bring us toward a decision. If we consider the use cases people generally have I'd say they generally want any phone number or a mobile phone only.

In that case `PhoneValidator.invalid(PhoneNumberType.mobile, 'Invalid mobile phone number');` might provide a better API. 

Or even:  `PhoneValidator.invalidMobile` & `PhoneValidator.invalidFixedLine` & `PhoneValidator.invalid`, which better handles error messages by default.

**Comment by emri99** [comment]
> In that case maybe `PhoneValidator.invalidMobile` & `PhoneValidator.invalidFixedLine` & `PhoneValidator.invalid`, would be more explicit.

Totally agree. Naming is hard and so important. Will update this way

However, I don't totally agree with your last assumption about required & composed validators as I have exactly this specific use case:

* missing field should display error : `You must enter a value`
* invalid phoneNumber should display : `Incorrect format`
* fixed line field should display : `This number is not a valid cellphone number`

Moreover, I think that as this is a very simple feature to implement, it's worth providing an easy way to achieve such needs even if majority of them would probably use only one validator without using composed validator.

**Comment by cedvdb** [comment]
Wouldn't this work ?

```
Validators.compose([
  Validators.required(),
  Validators.invalid('Incorrect format'),
  Validators.invalidMobile('This number is not a valid cellphone number'),
])
```
Or even:

```
Validators.compose([
  Validators.required(),
  Validators.invalid('Incorrect format'),
  Validators.invalidType(PhoneNumberType.mobile, 'This number is not a valid cellphone number'),
])
```

**Comment by emri99** [comment]
I've refactor code according to your advices.

```dart
PhoneValidator.required(context, ...),
PhoneValidator.invalid(context, ...)
PhoneValidator.invalidType(context, expectedType, ...)

// convenience method for PhoneValidator.invalidType(context, PhoneNumberType.mobile, ...)
PhoneValidator.invalidMobile(context, ...)  

// convenience method for PhoneValidator.invalidType(context, PhoneNumberType.fixedLine, ...)
PhoneValidator.invalidFixedLine(context, ...)
```

Can you please validate the default message in English so I can make the translations for others languages ? It's quite a repetitive tasks to translate in all supported languages, so I would like to avoid doing it twice as possible ;)
Note that I will use Deepl for this, tell me if you have a better solution/strategy ;)

--- 

I have another interrogation about deprecating `errorText` in `BasePhoneFormField`.
I did not find another solution than removing default value and make `errorText` nullable to ensure it will still work on both previous and new manner of handling validator.
However this seems like a breaking change as a standalone `BasePhoneFormField` ...
* without `errorText` supplied 
* and a custom validator not properly written (ie: not returning the String that user want to be displayed)

...may not flag a field as invalid if the validator is not properly defined. 
But as it seems to be like a bug on previous version (ie: the validator returned value was ignored due to the usage of `errorText` property), I think this an acceptable BC. Curious to hear what's your opinion about that ;)

**Comment by cedvdb** [comment]
Sorry for some reason I did not see your last message:

For your other PR I made a change to the translation files which are now .arb files and need to be generated with the command -`flutter gen-l10n` . The property keys must be valid dart property names though. So please either rebase on the localization_arb_fix branch or use already valid names so it will be easy for me to make the merge.

Therefor the properties should look like this:

```
  "phoneNumberRequired": "Phone number required",
  "phoneNumberInvalid": "Phone number invalid",
  "invalidCountry": "Invalid country", // although I'm not sure where that is displayed ?
  "invalidMobilePhoneNumber": "Invalid mobile phone number",
  "invalidFixedLinePhoneNumber": "Invalid fixed line phone number",
```

For the error text issue, tbh I did not understand exactly what you were saying. Does the field not become invalid when the errorText is not provided by the user ? If the field is marked as invalid when it is invalid I don't see an issue with a BC especially if it's a bug.

**Comment by emri99** [comment]
Sorry for the delay, this was a busy week.

* For the localization strings keys, I will update this. Be aware that it can introduce breaking change for english application as the PhoneFormLocalization was optional to get corrects invalid message. Updating this will make it required otherwise the camelCase string will be used instead ;)

* For the errorText,  if the errorText is not provided, it still flag the field as invalid with the previous default errorText as expected. The problem is only with the usage of `BasePhoneFormField` when supplying `validator` property. Previously, the validator output was not used because the `getErrorText` method was returning the widget `errorText` property and not the `errorText` state info. I maintain this weird behavior (seems more like a bug imho) to avoid breaking change. This may however create kind of a breaking change if validator was defined manually and not used properly.



Here's an example of a previous code that will be affected:

```dart
BasePhoneFormField(
  validator: (...) {
    if (/* check for invalid */) {
      return 'fake message not expected to be used as widget.errorText ' 
        'was displayed (validator output was ignored)';
    }
  } 
  //errorText not defined
)
```
With the above example :
* previously: the default previous constructor argument `errorText` was returned (ie: `Invalid phone number`)
* now: it will return the fake message above as I have removed the default `errorText` value and change it to a nullable String

**Comment by emri99** [comment]
Hmmm, due to the recently introduced localization changes (from `localization_arb_fix` branch), this PR is already breaking backward compatibility. 
Thus, I don't see the interest anymore in deprecating `errorText` & `phoneNumberType`, only cons (more complex, more error prone). What's your opinion about this ?

**Comment by cedvdb** [comment]
Yeah just go ahead and remove the unnecessary code, let's keep things simple

**Comment by emri99** [comment]
I don't think translations keys are problematics as they are not reals words anymore. At least in deepl, they aren't translated. 

FYI,  at work, according to our team mates who are native from others countries, we use deepl because they find it more efficient and it produces less word by word translations than google translations.

**Comment by emri99** [comment]
Ouch, I don't think the add-favorites feature should be included here. I've rebased on `localization_arb_fix` and it seems that this branche includes WIP code. I've squash my commits after rebasing so it looks like only [my last commit](https://github.com/cedvdb/phone_form_field/pull/16/commits/ad01229f32ad3ab656811b98d283b727718b5154) and yours addressing l10n issues should be included here.

Take a look and tell me if you want me to rebase/squash for a proper git history and/or separated features branches.

I've also updated CHANGELOG & README, don't hesitate to reword for better comprehension/english ;)

**Comment by cedvdb** [comment]
Ho damn, yeah I might have started from your other branch for that fix to see if it fixed your issue.

As you might have seen I'm not a git history maniac. However since this project is growing in size of contributors it will become increasingly important to have a standard clean git strategy.

So for future PR I'll adhere to the standard of squashing for pull request and not mixing things up. 

Concerning this one, the git history here just has too many files to do a clean review. If you already rebased, fixed the comments and the test pass I'm okay with either (merging this as is or merge before your rebase). 

What I propose though, is merging the other merge request first. The one with validation (I merged it on a separate branch in order to create the flutter issue) but it eventually needs to be merged in dev. That flutter issue has been reproduced by the flutter team btw.

**Comment by emri99** [comment]
I can merge my last changes done yesterday about favorites countries in this one (I've added few tests), resolve conflicts with current dev branch and ensure that all tests are passing so you have only this PR to accept.

Is this ok for you ?
I hope I can do this in the evening/night or tomorrow at most :)

**Comment by cedvdb** [comment]
Yes that would be perfect. Then a new major version could be released beginning of next week. I've a breaking change I need to introduce as well and now is a good time.

**Comment by emri99** [comment]
My idea is to have favorites countries feature and custom validator feature in this PR. I will perform rebase or cherry pick (I don't really know currently what will be the easiest/secured way) to have a forward history related to current dev branch.

**Comment by cedvdb** [comment]
Not sure if it will help but I've refactored the inputs in a branch called `refactor_controllers_form_field`. If you hit a problem it might be fixed there as it seems it fixed multiple issues.

**Comment by emri99** [comment]
I haven't work yesterday evening due to lack of sleep. Seing your message, I think this was a good idea, as I would probably had squash the `localization_arb_fix` to perform a rebase without having to resolve conflicts on each of your commit.
As your new fix branch start from `localization_arb_fix`, squashing is not an option anymore.
Although it will give me more work, this may be a better strategy to start working from your last development. In this way, if you are confident with latests fixes introduced in your fresh refactor branch, it may be a good idea to merge your code into `dev` branch, and I will manage to update my code from this new starting point.

However those last changes will produce a lot of friction with my current development. I don't know how it can be addressed easily. I won't surprised if it forces me to refactor lots of the new features code.

**Comment by cedvdb** [comment]
Oh, you don't have to rebase on my latest fixes dude, my plan was to wait for your PR, I just did some prepary work to see if my refactor idea could work. 

I was just letting you know that there is a new branch  where the code is a bit easier to understand. I'll do the merge after don't worry. Of course if you want to rebase anyway you are welcome to do it but that's certainly not a requirement

**Comment by emri99** [comment]
I just notice that the `BasePhoneFormField` is not a `FormField` anymore in your last refactored branch. I'm not sure of the consequences of this change, but I'm very worried about this and usage of this widget inside a form, as well for submitting data and retrieving it, data validation, autovalidation features, and all the handling previously done by form field.
The validation I've add seems almost useless, at least obsolete with this way of handling data. Either the package/widget name are pretty confusing too. Sure you wan't to refactor this in the upcoming next version ? (I think this needs more tests in a Form context to ensure that the package will still be usable)

**Comment by cedvdb** [comment]
Before PhoneFormField was a `StatefulWidget` and base was `FormField` now it's the opposite. Making them both `FormField` is an option though. 

No the refactor does not have to be in the upcoming version.

**Comment by emri99** [comment]
I miss the fact that it has been swapped between `PhoneFormField` and `BasePhoneFormField`.
Thanks for this clarification ;)

**Comment by cedvdb** [comment]
Is that okay if I merge this on a lateral branch to apply the fixes on it myself or have you started ?

**Comment by emri99** [comment]
I don't understand the produced diff, a lots of files are fully modified but contents is the same. Did you change formatting ? spaces/tabs ?

**Comment by cedvdb** [comment]
I have merged the changes from this branch onto my other branch. There is just 2 files with errors regarding validation. 

I ve done it on that branch `validation_favs`, does that help ?

**Comment by emri99** [comment]
When I switch onto `validations_favs` I've got 16 errors on my side

**Comment by cedvdb** [comment]
there should be 5 now

**Comment by emri99** [comment]
Got 6 ;) but I'm still on flutter 2.2.3 because my work app cannot be upgraded until all dependencies have been updated.
Currently upgrading to 2.5.1 for this project only...

**Comment by cedvdb** [comment]
What dart sdk version are you on ?

**Comment by emri99** [comment]
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3 20E232 darwin-x64, locale fr-FR)
    • Flutter version 2.2.3 at /Users/emri/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
```

**Comment by emri99** [comment]
I notice that you have removed usage of the light parser in the validator class, but not the arguments `useLightParser` is this present. just a missed point or volontary ? ;)

Noticed too, that I forgot to remove a comment I made to validate a test (`phone_validator.dart:61-62`) ;)

**Comment by cedvdb** [comment]
That is a missed point. light parser is not used anymore. Actually in the way it was included it never was.

**Comment by cedvdb** [comment]
https://gitter.im/cedvdb/phone_form_field I've created a gitter for discussion

**Pull request closed without merging**
