### PR TITLE
added missing RU localizations

### PR DESCRIPTION
**Pull request by michep**
added missing RU localizations, please merge

### CODE REVIEW

**Comment by cedvdb** [comment]
Can you run dart fix --apply please

**Comment by michep** [comment]
done dart fix --apply

**Review by cedvdb — COMMENTED** [review]
LGTM

**Review by cedvdb — APPROVED** [review]
LGTM

**Comment by michep** [comment]
would you please update pub.dev version as I still can not see changes with 'dart pub add phone_form_field'

**Comment by sapar-io** [comment]
How can I use this RU russian localization? There is no RU in pub.dev package

**Pull request merged**
