### PR TITLE
Two Improvements to the field:

### PR DESCRIPTION
**Pull request by moazelsawaf**
Hello Dear,

Firstly, thank you for your hard work to help the Flutter Community. secondly, kindly review these two improvements that I have made, tested, and already used in my app:

- Added a property called 'countryCodeStyle' to allow the customization of the TextStyle of country code.
- Considering the size of the prefix icon ( if used ) while calculating the width of the CountryCodeChip InkWell.

Thanks.
Moaz El-sawaf

### CODE REVIEW

**Comment by cedvdb** [comment]
For the width thing I think it would be better if there was another invisible countryCode inside the inkwell so the width is automatically set.

It used to be this way but in the last upgrade I made which needed quite some rework of the internals I forgot the add that.

**Comment by moazelsawaf** [comment]
But does that one takes care of the width while using a prefixIcon?

**Comment by cedvdb** [comment]
Oh so you are adding a phone icon as prefix icon or something like that ?

**Comment by moazelsawaf** [comment]
Exactly, In the attached image I am showing the implemented UI, the implementation in the current latest stable version is not considering the existence of prefixIcon in the field while calculating the width of the InkWell.

**Comment by cedvdb** [comment]
Thank you

**Comment by moazelsawaf** [comment]
My pleasure 🙏🏻❤️

**Pull request merged**
