### PR TITLE
update README.md and example

### PR DESCRIPTION
**Pull request by rashidotm**
this pr is to update code samples in readme and in exmaple

### CODE REVIEW

**Comment by rashidotm** [comment]
this fixes #241

**Comment by cedvdb** [comment]
I'm confused why the example compiled and was uploaded to github page if it was erroneous like that

**Comment by cedvdb** [comment]
It seems like you are using an old version in example or something. If you check the validation code for example, they all take a context but you removed the context:

https://github.com/cedvdb/phone_form_field/blob/main/lib/src/validation/phone_validator.dart#L55

**Comment by rashidotm** [comment]
This is embarrassing!

You are right. I was using an old version and haven't noticed till you pointed it out.

**Comment by rashidotm** [comment]
closing this as the version used was not latest.

**Comment by cedvdb** [comment]
@rashidotm did you clone the repository a long time ago ?

**Pull request closed without merging**
