### PR TITLE
fix a logical bug

### PR DESCRIPTION
**Pull request by xmine64**
well `widget.textDirection == TextDirection.rtl && widget.TextDirection == null` is always false.

### CODE REVIEW

**Comment by cedvdb** [comment]
Can you add a test for RTL ?

**Comment by xmine64** [comment]
I'm not good at writing UI tests, but I added RTL option to example to see it it works or not.

**Comment by cedvdb** [comment]
The testing file is straight forward https://github.com/cedvdb/phone_form_field/blob/dev/test/phone_form_field_test.dart

it will be something along the lines of:

```dart
      testWidgets('Should have RTL support', (tester) async {
        await tester.pumpWidget(
            getWidget(
               textDirection: TextDirection.rtl
            ),
        );
        final stackFinder = find.byType(Stack); // might have to use find.byKey here
        final stackWidget = tester.widget<Stack>(stackFinder)
        final textFieldFinder = find.byType(TextField);
        final textFieldWidget = tester.widget<TextField>(textFieldFinder);
        expect( stack.textDirection, equals(TextDirection.rtl));
        expect( textFieldWidget.decoration.suffix != null, isTrue);
        expect( textFieldWidget.decoration.prefix == null, isTrue);
      });
```

**Comment by xmine64** [comment]
> it will be something along the lines of

Sure, this seems nice but still it can't confirm country chip and the InkWell are in their correct position, can it?

**Comment by cedvdb** [comment]
It does test that the correct parameters are sent to the flutter widget. Flutter is responsible to put the suffix at the end, and the prefix at the beginning. A rule of testing is that you do not unit test what you do not own. So it covers enough regarding the prefix / suffix. As for the stack it's harder to tell, but this should be enough.

**Comment by xmine64** [comment]
Now that I think country chip should always be prefix, as you have a InputDecoration inside another one maybe we can just change directionality of inner decoration instead. It seems more logical.
Another question, can't you just wrap country chip with InkWell, instead of adding it on top of country chip? Prefix/suffix can't be clickable?

**Comment by cedvdb** [comment]
> Another question, can't you just wrap country chip with InkWell, instead of adding it on top of country chip?

I would love if that was doable but unfortunately no, this is the first thing I tried. The prefix is supposed to be a certain height and width and the input has padding inside it. 

Actually, now that I think of it though, when I tried this it was maybe directly on the  inner input decoration as there was only one input before (without an additional InputDecorator above it).  So there might be a way in now.. It would probably require to have an empty padding for the outter input so the inkwell can take the whole height. This would also remove the need for the `MeasureSize` thing that I also hate.  That'd be amazing.

This input has evolved quite a lot since I always hated the fact that I had to put those kind of hacks inside it.

> we can just change directionality of inner decoration instead 

There is the stack above.

**Comment by xmine64** [comment]
I got it now, I'm not sure if it's possible or not but I'll take a look at it.

**Comment by cedvdb** [comment]
Thanks for adding tests. I will check it out later

**Comment by xmine64** [comment]
I made some big changes, I moved country chip to inner input decoration and used `Directionality` widget to set position of input decoration prefix. this one looks less hacky than previous fix, country chip is still a prefix but it would be on left or right based on textDirection, instead of using suffix to move it to left.

**Comment by cedvdb** [comment]
This was merged then reverted. It seems a bug is still present.

image

**Comment by xmine64** [comment]
Well we don't right numbers in rtl, i guess we should just remove textDirection field and always use ltr for the field.

**Comment by cedvdb** [comment]
> Well we don't right numbers in rtl

Isn't it just another set of numbers ? ١٢٣

This would be a really nice feature to have as the phone parser library should allow those characters.

**Comment by xmine64** [comment]
> Isn't it just another set of numbers ? ١٢٣

Yes they're same as 123 but just with another look. Everything about them is same as English digits, We write them in LTR.
As workaround in my project I convert them to English digits and then I use the result.

```
extension StringToPersianIntFormatterX on String {
  /// Convert a string with Persian digits to integer
  int? persianToInt() {
    final digitsMap = {
      '0': '۰',
      '1': '۱',
      '2': '۲',
      '3': '۳',
      '4': '۴',
      '5': '۵',
      '6': '۶',
      '7': '۷',
      '8': '۸',
      '9': '۹',
    };
    var target = this;
    for (final digit in digitsMap.entries) {
      target = target.replaceAll(digit.value, digit.key);
    }
    return int.tryParse(target);
  }
}
```

**Pull request merged**
