### PR TITLE
New customization properties to the `CountrySelectorNavigator`

### PR DESCRIPTION
**Pull request by moazelsawaf**
Hello,

I have added some new customization properties to the `CountrySelectorNavigator` which are the following:
- For the `CountryList`, properties to customize the `titleStyle` & `subtitleStyle` for all the `CountrySelectorNavigator`s, not just the `BottomSheetNavigator`, and a property to customize the `scrollPhysics` of the list.
- For the `SearchBox`, properties to customize the `InputDecoration`, `TextStyle`, and Search Icon Color`.

I hope you like them.

Thanks ❤
Moaz El-sawaf

### CODE REVIEW

**Comment by Jmy-dev** [comment]
OMFG this PR is awesome pls  merge it man @cedvdb !!

**Comment by cedvdb** [comment]
Yes it's only been two days mate 😋

**Comment by moazelsawaf** [comment]
Please would you release a new updated to pub.dev soon including this PR? 💙

**Comment by cedvdb** [comment]
Yes it is waiting for another update in the parser library and one in the phone metadata library

**Comment by moazelsawaf** [comment]
Nice, I hope to see this soon ❤️

**Comment by cedvdb** [comment]
@moazelsawaf one of the two PR I'm waiting for has landed, the other one should be in soon too.

**Comment by cedvdb** [comment]
added in v 7.0.2, the underlying phone number parser library had a major version release so tell me if there is any issue (that parser library is also mine)

**Comment by moazelsawaf** [comment]
Great, of course I will Insha'Allah ❤

**Pull request merged**
