### PR TITLE
fix: RTL not supported correctly #220

### PR DESCRIPTION
**Pull request by yousefak007**
#220

### CODE REVIEW

**Comment by cedvdb** [comment]
Thanks for the fix. 

Could you remove the changes regarding mirror in this PR and concentrate on fixing the RTL ?

I don't think mirror should be added in this PR, actually I don't think it should be added at all, but that's up for discussion.

**Comment by yousefak007** [comment]
a few Points:

- `textDirection` is always LTR, in Latian language or Arabic language, so I will make it as default 
- `mirror` is not clear, I made  `CountryButtonSide` enum and have `{prefix, suffix}` and the default is `prefix`

>  Just settle on the one that makes the more sense from your perspective
it is hard to decide which one is preferred because of the different areas

I think `CountryButtonSide` because now it is independent of the direction, you can change it in LTR or RTL mode, and I make the default value a `prefix`

also, I updated the example try it maybe it will be clear for you

**Comment by yousefak007** [comment]
for my clients, I always use it in RTL with suffix

image

but some people use it in RTL with prefix

image

**Comment by cedvdb** [comment]
Seeing those issues I'd advice adding tests so this does not break in the future.

**Comment by yousefak007** [comment]
but how can we align the country code and phone number to the right and the text direction as LTR?

also, google uses it on the right.

in my last update, I think I made it acceptably. so, If you see you will not add it, maybe I can make a fork from this project and upload it to `pub.dev` as a new package

**Comment by cedvdb** [comment]
I want this in the package:

image

 with tests.

**Comment by cedvdb** [comment]
I'll do a release by the end of the week with some PR's that have been merged in the underlying packages. Should I wait for this one ?

I'm asking because you said:

> in my last update, I think I made it acceptably. so, If you see you will not add it, maybe I can make a fork from this project and upload it to pub.dev as a new package

Which sounds like you won't fix

**Comment by yousefak007** [comment]
Hi @cedvdb, I sincerely apologize. I have been and still am busy and have been unable to make the necessary updates and create the necessary tests.

Therefore, you can bypass this PR or you have the freedom to make the necessary modifications and updates if you want

Thank you again

**Comment by cedvdb** [comment]
Should be fixed by https://github.com/cedvdb/phone_form_field/pull/230

**Pull request closed without merging**
