### PR TITLE
Add an option that Make the country chip fixed on one Direction suffix/prefix 

### PR DESCRIPTION
**Pull request by mohn93**
Add countryChipDirection option, which will fixate the direction of the country chip either on prefix or suffix

### CODE REVIEW

**Comment by cedvdb** [comment]
Is the country chip supposed to be on the right for phone numbers or on the left ?


I would like one option that works well, either the chip is on the right or left depending on RTL or LTR directionality context. This seems to add more customization but I'm more in favor of having the input RTL or LTR, without too much customization to alleviate additional complexity.

**Comment by mohn93** [comment]
I don't see how this can be complex for the user!

The current implementation already moves the chip to RTL/LTR based on the directionality coming from the context,
So what I did is just add the option of fixating the country chip to one side regardless of the app's directionality, LTR, or RTL.

**Comment by mohn93** [comment]
@cedvdb, Alright, I'll add a test for this one

**Comment by cedvdb** [comment]
> So what I did is just add the option of fixating the country chip to one side regardless of the app's directionality, LTR, or RTL.
 
Yes and I'm suggesting having one way only without customization. That is either the phone form field is LTR or RTL, if the chip needs to be on the right for RTL then it doesn't need to be customizable.

> I don't see how this can be complex for the user!

I doubt there is an use in picking a side for the flag for the end user. Adding unnecessary complexity to a library without a valid use case is the issue.

**Comment by mohn93** [comment]
@cedvdb, I see, Well I think no one is using the RTL layout here, even the RTL languages, so based on that we should fixate the chip to be always on the left side, what do you say to that?

**Comment by cedvdb** [comment]
Yes I'm okay with that, I think you know better which side it is supposed to be for RTL language.

So if I understand you correctly, in RTL languages the input is supposed to look like this:

`[(chip)______________phonenumber]` 

instead of 

`[phonenumber_____________(chip)]`

Either one is fine for me, unfortunately I don't read RTL so I'll let someone like you decide which side it is supposed to be in in those language.

**Comment by cedvdb** [comment]
> Tell me what's the next step, should I add another commit containing this change?

Yes please or close this one and reopen another if easier.

**Pull request closed without merging**
