### PR TITLE
Add Hungarian localization messages

### PR DESCRIPTION
**Pull request by emri99**
# Content

* New supported language : Hungarian

## Notice

Changes on existing generated files seems useless & only related to formatter.

I've used flutter 3.19.3 and command `flutter gen-l10n`.

* If you want me to fix generated files, can you tell me how you generate them ?
* I can remove the last commit if you prefer to build them by yourself ;)

### CODE REVIEW

**Comment by cedvdb** [comment]
You can just run `dart fix --apply` to fix the generated files

**Comment by cedvdb** [comment]
I don't know what's up with those line length, it seems to change in every other PR and I let it pass. So honnestly just push it with `dart fix --apply` and with the line length changes.

**Comment by emri99** [comment]
Generated files updated & push-forced. Let me know if anything else should be changed ;)

**Review by cedvdb — APPROVED** [review]

**Comment by emri99** [comment]
Sorry to bother you, do you have planned to release a version including this update ?

Thanks again for your hard work

**Comment by cedvdb** [comment]
Thanks, I'll do it this evening

**Comment by cedvdb** [comment]
It's going to be in the upcoming days, I'm fixing a few issues.

**Comment by emri99** [comment]
Perfect ! Thanks for the info ;)

**Comment by cedvdb** [comment]
Not sure why you did not add all hu message but I'm adding the remaining ones via google translate since i'm doing it for each missing translation:

```
  "selectACountrySemanticLabel": "Seleziona un paese, selezione attuale: {countryName} {dialCode}",
  "@selectACountrySemanticLabel": {
    "description": "semantic description of the country button",
    "placeholders": {
      "countryName": {
        "type": "String"
      },
      "dialCode": {
        "type": "String"
      }
    }
  },
  "phoneNumber": "Numero di telefono",
  "currentValueSemanticLabel": "Valore corrente: {currentValue}",
  "@currentValueSemanticLabel": {
    "description": "semantic description of the phone input. The label or hint will be dynamically added",
    "placeholders": {
      "currentValue": {
        "type": "String"
      }
    }
  }

```

**Comment by emri99** [comment]
Hmm... Neither do I ! Sorry for that !

**Comment by cedvdb** [comment]
No problem, I've added language selection to the demo if you want to check the hungarian language https://cedvdb.github.io/phone_form_field/

**Comment by emri99** [comment]
Check done ! No problem found ;)

**Pull request merged**
