### PR TITLE
FEAT: show selected country iso code feature implemented

### PR DESCRIPTION
**Pull request by Hpaneru**
This allows showing the selected country iso code, by default it is false.

### CODE REVIEW

**Comment by cedvdb** [comment]
Can you be a bit more specific in the description ?

Is it showing the isoCode instead of the input ? Is this actually needed ?

**Comment by Hpaneru** [comment]
Hi @cedvdb , yup there is a boolean flag showIsoCodeInInput, false by default. If it is true then the currently picked or selected country's iso code will be shown in the left side of the flag.

**Comment by cedvdb** [comment]
Can you double check that things are still aligned in the example by playing with:

  - border: outline vs underline
  - hint on or off
  - persistent country on off 
  - etc.

I will double check it too but it's going to be merged faster if there is no issue. This was a nightmare to get right, at least vertically

**Comment by Hpaneru** [comment]
Hi @cedvdb, Actually I am talking about one boolean flag to show the selected country's iso code. It is false by default. 
It won't be showing instead of input It will be shown in the left side of the flag. Please find the attachment with this comment. Currently, in the attachment I have selected the Australia an the iso code of Australia is AU that is shown just in the left side of the flag. But in my case I don't want to show the flag so the flag is missing in the attachment!
Screenshot 2023-09-13 at 15 25 08

**Comment by cedvdb** [comment]
Is this screenshot from a design software or from the input itself ? Because I don't think it's currently possible to have two separate borders from this library like in the screenshot. Ence why I'm wondering if the api shouldn't be lower level to allow designs like that.

**Comment by Hpaneru** [comment]
Yup! the separate border is not currently possible from the package itself, It is designed by myself for my use case. But in the pr, i have just added the the feature which shows the selected country iso code, like "AU" in the above attachment.

Great, thanks for taking care of that! Let me know if you need any help or if there are any updates.

**Pull request merged**
