### PR TITLE
fix: force LTR direction even in RTL context

### PR DESCRIPTION
**Pull request by xmine64**
This commit keeps direction of outer `InputDecoration`, while forces inner decoration to use LTR even if app is RTL, because numbers are always written from left to right.

It also moves country chip to inner `InputDecoration`, to keep it before phone number.

### CODE REVIEW

**Comment by cedvdb** [comment]
The analysis failed

**Comment by cedvdb** [comment]
I don't think it's supposed to be like this ?

image

**Comment by xmine64** [comment]
> I don't think it's supposed to be like this ?

Yes, Numbers are LTR always.

I want it like that, instead of like this:
image

Other RTL fields with LTR textDirection:
image

**Comment by cedvdb** [comment]
Oh perfect ! 

The tests you added the last time are not part of the repository anymore. If you could add the appropriate test (even reuse the one from the last PR) I can merge and push to pub.dev.

There are additional pull request which passed so this would be a nice addition

**Comment by cedvdb** [comment]
Can you fix the issues above so we can go ahead and merge this ?

**Comment by cedvdb** [comment]
Just to be clear there is nothing to add in the repository then ? except forcing LTR ? inside the input ?

**Comment by xmine64** [comment]
Yes, sorry I didn't write test, I've been busy for a while and still I'm busy, but I forgot.

**Comment by cedvdb** [comment]
it's okay, I added the last test you did in my PR, I'll merge and push this evening

**Pull request closed without merging**
