### PR TITLE
FEAT: optional separator added in between country code and phone number

### PR DESCRIPTION
**Pull request by Hpaneru**
An optional separator widget adde in between the country code and phone number.

### CODE REVIEW

**Comment by cedvdb** [comment]
This seems like this is very specific to your use case. I'm not sure it's a good idea to fit every use case out there via properties.

Maybe a builder of some sort would be better.

**Comment by Hpaneru** [comment]
Hi @cedvdb Have you gone through the changes??

**Comment by cedvdb** [comment]
@Hpaneru Hi sorry, I've been pretty busy lately. I'll check it out now

**Comment by cedvdb** [comment]
looks good, please rename the parameter to something like "country button suffix" or something like that as this is not really a separator.

**Comment by Hpaneru** [comment]
sure @cedvdb will let you know ones it is done! I am also busy with some other tasks. Once I get time, I will rename that.

**Comment by 2shrestha22** [comment]
@Hpaneru any update on this?

**Comment by cedvdb** [comment]
@2shrestha22 

You can resubmit the PR if needed.

**Comment by cedvdb** [comment]
There is now a dropdown icon by default in v9.0.1

**Pull request closed without merging**
